/*$file${.::test.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: test.qm
* File:  ${.::test.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::test.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h"    /* QP-nano framework API */
#include "bsp.h"    /* Board Support Package interface */

/* ask QM to declare the Test class --------------------------------------*/
/*$declare${AOs::Test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Test} .............................................................*/
typedef struct Test {
/* protected: */
    QActive super;
} Test;

/* protected: */
static QState Test_initial(Test * const me);
static QState Test_off(Test * const me);
static QState Test_on(Test * const me);
/*$enddecl${AOs::Test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* the single instance of the Blinky active object -------------------------*/
Test AO_Test;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Test_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Test_ctor} ........................................................*/
void Test_ctor(void) {
    Test * const me = &AO_Test;
    QActive_ctor(&me->super, Q_STATE_CAST(&Test_initial));
}
/*$enddef${AOs::Test_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Test} .............................................................*/

/*${AOs::Test::SM} .........................................................*/
static QState Test_initial(Test * const me) {
    /*${AOs::Test::SM::initial} */
    /* arm the private time event for tick rate 0
    * to expire in 1/2s and periodically every 1/2 second
    */
    QActive_armX(&me->super,
                 1U,
                 BSP_TICKS_PER_SEC_1,
                 10);
    return Q_TRAN(&Test_off);
}

/*${AOs::Test::SM::off} ....................................................*/
static QState Test_off(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::off} */
        case Q_ENTRY_SIG: {
            BSP_ledOffH();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Test::SM::off::Q_TIMEOUT} */
        case Q_TIMEOUT1_SIG: {
            status_ = Q_TRAN(&Test_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Test::SM::on} .....................................................*/
static QState Test_on(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::on} */
        case Q_ENTRY_SIG: {
            BSP_ledOnH();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Test::SM::on::Q_TIMEOUT} */
        case Q_TIMEOUT1_SIG: {
            status_ = Q_TRAN(&Test_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
